# Generated by Django 5.0.4 on 2024-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.CharField(max_length=100)),
            ],
        ),
    ]
