# Generated by Django 5.0.4 on 2024-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drag', '0003_yourmodel_field10_yourmodel_field11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='field13',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='field14',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
