# Generated by Django 5.0.4 on 2024-05-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drag', '0005_yourmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='margin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
