# Generated by Django 5.0.4 on 2024-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drag', '0006_category_margin_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('countrynameeng', models.CharField(blank=True, db_column='CountryNameEng', max_length=255, null=True)),
                ('countrynamejpn', models.CharField(blank=True, db_column='CountryNameJpn', max_length=255, null=True)),
                ('uppercode', models.CharField(blank=True, db_column='UpperCode', max_length=255, null=True)),
                ('lowercode', models.CharField(blank=True, db_column='LowerCode', max_length=255, null=True)),
                ('nacsscountryid', models.CharField(blank=True, db_column='NacssCountryId', max_length=2, null=True)),
                ('uncode', models.CharField(blank=True, db_column='UnCode', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customercategory',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('categorynameeng', models.CharField(db_column='CategoryNameEng', max_length=100)),
                ('categorynamejpn', models.CharField(db_column='CategoryNameJpn', max_length=255)),
                ('margin', models.IntegerField(blank=True, db_column='Margin', null=True)),
                ('createddatetimeutc', models.DateTimeField(db_column='CreatedDateTimeUtc')),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=250)),
                ('updateddatetimeutc', models.DateTimeField(db_column='UpdatedDateTimeUtc')),
                ('updatedby', models.CharField(db_column='UpdatedBy', max_length=250)),
            ],
            options={
                'db_table': 'CustomerCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customercompany',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('companynameeng', models.CharField(db_column='CompanyNameEng', max_length=100, unique=True)),
                ('companynamejpn', models.CharField(db_column='CompanyNameJpn', max_length=255, unique=True)),
                ('primarypepresentative', models.CharField(db_column='PrimaryPepresentative', max_length=100)),
                ('secondarypepresentative', models.CharField(blank=True, db_column='SecondaryPepresentative', max_length=100, null=True)),
                ('officepostbox', models.CharField(db_column='OfficePostBox', max_length=20)),
                ('officeprefectureeng', models.CharField(db_column='OfficePrefectureEng', max_length=100)),
                ('officeprefecturejpn', models.CharField(db_column='OfficePrefectureJpn', max_length=100)),
                ('officecityeng', models.CharField(db_column='OfficeCityEng', max_length=100)),
                ('officecityjpn', models.CharField(db_column='OfficeCityJpn', max_length=100)),
                ('officeaddresseng', models.CharField(db_column='OfficeAddressEng', max_length=500)),
                ('officeaddressjpn', models.CharField(db_column='OfficeAddressJpn', max_length=500)),
                ('officephone', models.CharField(db_column='OfficePhone', max_length=255, unique=True)),
                ('officefax', models.CharField(db_column='OfficeFax', max_length=255, unique=True)),
                ('custompostbox', models.CharField(db_column='CustomPostBox', max_length=20)),
                ('customprefectureeng', models.CharField(db_column='CustomPrefectureEng', max_length=100)),
                ('customprefecturejpn', models.CharField(db_column='CustomPrefectureJpn', max_length=100)),
                ('customcityeng', models.CharField(db_column='CustomCityEng', max_length=100)),
                ('customcityjpn', models.CharField(db_column='CustomCityJpn', max_length=100)),
                ('customaddresseng', models.CharField(db_column='CustomAddressEng', max_length=500)),
                ('customaddressjpn', models.CharField(db_column='CustomAddressJpn', max_length=500)),
                ('iecode', models.CharField(blank=True, db_column='IECode', max_length=100, null=True)),
                ('mailingpostbox', models.CharField(db_column='MailingPostBox', max_length=20)),
                ('mailingprefectureeng', models.CharField(db_column='MailingPrefectureEng', max_length=100)),
                ('mailingprefecturejpn', models.CharField(db_column='MailingPrefectureJpn', max_length=100)),
                ('mailingcityeng', models.CharField(db_column='MailingCityEng', max_length=100)),
                ('mailingcityjpn', models.CharField(db_column='MailingCityJpn', max_length=100)),
                ('mailingaddresseng', models.CharField(db_column='MailingAddressEng', max_length=500)),
                ('mailingaddressjpn', models.CharField(db_column='MailingAddressJpn', max_length=500)),
                ('companyremarks', models.TextField(blank=True, db_column='CompanyRemarks', null=True)),
                ('picturestoclick', models.CharField(db_column='PicturesToClick', max_length=250)),
                ('status', models.CharField(db_column='Status', max_length=20)),
                ('createddatetimeutc', models.DateTimeField(db_column='CreatedDateTimeUtc')),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=250)),
                ('updateddatetimeutc', models.DateTimeField(db_column='UpdatedDateTimeUtc')),
                ('updatedby', models.CharField(db_column='UpdatedBy', max_length=250)),
            ],
            options={
                'db_table': 'CustomerCompany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Freight_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POL', models.CharField(blank=True, max_length=100, null=True)),
                ('POD', models.CharField(blank=True, max_length=100, null=True)),
                ('LINER', models.CharField(blank=True, max_length=100, null=True)),
                ('TYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('THC', models.CharField(blank=True, max_length=100, null=True)),
                ('field6', models.CharField(blank=True, max_length=100, null=True)),
                ('CONTAINER', models.CharField(blank=True, max_length=100, null=True)),
                ('field8', models.CharField(blank=True, max_length=100, null=True)),
                ('CONTAINER_PRICE', models.CharField(blank=True, max_length=100, null=True)),
                ('SAEL_AMOUNT', models.CharField(blank=True, max_length=100, null=True)),
                ('FREE_FEE', models.CharField(blank=True, max_length=100, null=True)),
                ('FREE_DAYS', models.CharField(blank=True, max_length=100, null=True)),
                ('VALIDITY_FROM', models.CharField(blank=True, max_length=100, null=True)),
                ('VALIDITY_TO', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
